client:
  port: 8080
  debug: false
  path: "/app"  # <--- THAY ĐỔI DÒNG NÀY: Mặc định nó là "./client/dist"
  api_key: "TN_Admin_Key_2026"
  secret: "TN_Secret_Key_Super_Secure_2026"
  token_validity: 10m
  copyright_conf:
    display: false
    text: 'Powered by NextGen Meet'
