# Lấy bản NATS nguyên gốc
FROM nats:2.10-alpine

# Copy file cấu hình trên Github của bạn vào đúng vị trí bên trong NATS
COPY nats_server_sample.conf /etc/nats/nats-server.conf

# Chỉ chạy bằng lệnh nạp file config, bỏ các lệnh port gây xung đột
CMD ["-c", "/etc/nats/nats-server.conf"]
